# 개발환경 dev > 배포 시 prod 변경
env: "prod" # "local" | "dev" | "prod"

spring:
  profiles:
    include:
      - secret
    active: ${env}
  application:
    group: backend
    name: common
    version: 1.0.0
#  banner:
#    location: # 배너 텍스트 리소스 위치.

  graphql:
    enabled: true
#    schema:
#      resources/graphql/**/*.graphqls 를 자동으로 읽음
#      locations: classpath:graphql/**/*.graphqls
    endpoint:
      path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
      cdn:
        enabled: false

#  graphql:
#    # GraphQL 자동 설정 비활성화 (커스텀 설정 사용)
#    enabled: false
##    path: .graphql
#graphql:
#  # 도메인별 엔드포인트
#  endpoints:
#    code: "/graphql/code"
#    org: "/graphql/org"

springdoc:
  swagger-ui:
    #    default path = /swagger-ui.html
    path: /${spring.application.name}/swagger-ui.html
  #    config-url: /${spring.application.name}/v3/api-docs/swagger-config
  api-docs:
    path: /${spring.application.name}/v3/api-docs
# proxy 사용 시 권장설정
server:
  forward-headers-strategy: FRAMEWORK

# 개별 서비스 인증 관리
app:
  jwt:
    whitelistUrls:
      - /error
      - /test/**
    adminOnlyUrls:
      - /admin/**
      - /swagger/**
      - /swagger-ui/**



