# 개발환경 dev > 배포 시 prod 변경
env: "prod" # "local" | "dev" | "prod"

spring:
  profiles:
    include:
      - secret
    active: ${env}
  application:
    group: backend
    name: common
    version: 1.0.0
#  banner:
#    location: # 배너 텍스트 리소스 위치.

springdoc:
  swagger-ui:
    #    default path = /swagger-ui.html
    path: /${spring.application.name}/swagger-ui.html
  #    config-url: /${spring.application.name}/v3/api-docs/swagger-config
  api-docs:
    path: /${spring.application.name}/v3/api-docs
# proxy 사용 시 권장설정
server:
  forward-headers-strategy: FRAMEWORK

app:
  jwt:
    expiration:
      access: 10
    whitelistUrls:
      - /error
      - /test/**
    adminOnlyUrls:
      - /admin/**
      - /swagger/**
      - /swagger-ui/**